FROM golang:1.13.8 as builder
WORKDIR /go/src/github.com/influxdata/influxdb
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o influxd ./cmd/influxd

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /go/src/github.com/influxdata/influxdb/influxd /usr/bin/influxd
EXPOSE 8086
CMD ["influxd"] 